misconfigurations:
  - id: AVD-KSV-0041 # Piggy needs to read secrets
  - id: AVD-KSV-0048 # Piggy needs to mutate pods
  - id: AVD-KSV-0049 # Piggy needs to read configmap
  - id: AVD-KSV-0110 # Should set metadata.namespace to a non-default namespace
  - id: AVD-KSV-0125 # Uses an image from an untrusted registry
skip-dirs:
  - "./demo/*" 