apiVersion: v1
kind: Pod
metadata:
  name: demo
  annotations:
    piggysec.com/piggy-address: https://piggy-webhooks.piggy-webhooks.svc.cluster.local
    piggysec.com/aws-ssm-parameter-path: /demo/sample/test
    piggysec.com/aws-region: ap-southeast-1
spec:
  serviceAccountName: demo
  containers:
    - image: ghcr.io/kongz/piggy-demo:latest
      name: demo
      env:
        - name: TEST_ENV
          value: piggy:TEST_ENV
        - name: TEST_LIST
          value: piggy:TEST_LIST
        - name: TEST_PLAIN
          value: piggy:TEST_PLAIN
      resources:
        limits:
          memory: "64Mi"
          cpu: "200m"