{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piggy-webhooks.serviceAccountName" . }}
  labels:
    {{- include "piggy-webhooks.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Requried aws.roleArn" .Values.aws.roleArn }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
