{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piggy-webhooks.serviceAccountName" . }}
  labels:
    {{- include "piggy-webhooks.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- if .Values.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
  {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
