apiVersion: v1
kind: Pod
metadata:
  name: demo
  annotations:
    piggy.kong-z.com/piggy-address: https://test-piggy-webhooks.piggy-test.svc.cluster.local
    piggy.kong-z.com/aws-secret-name: demo/sample/test
    piggy.kong-z.com/aws-region: ap-southeast-1
spec:
  containers:
    - image: 534625442569.dkr.ecr.ap-southeast-1.amazonaws.com/test/piggy-demo:latest
      name: demo
      env:
        - name: TEST_ENV
          value: piggy:TEST_ENV
      resources:
        limits:
          memory: "64Mi"
          cpu: "200m"