name: Build to GHCR
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Get version
        id: version
        run: |
          echo ::set-output name=value::"${GITHUB_REF#refs/tags/}"
      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build piggy-env and push
        id: docker_piggy-env
        uses: docker/build-push-action@v4
        with:
          context: ./piggy-env
          build-args: |
            VERSION=${{ steps.version.outputs.value }}
          file: ./piggy-env/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kongz/piggy-env:${{ steps.version.outputs.value }},ghcr.io/kongz/piggy-env:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: piggy-env digest
        run: echo ${{ steps.docker_piggy-env.outputs.digest }}
      - name: Build piggy-webhooks and push
        id: docker_piggy-webhooks
        uses: docker/build-push-action@v4
        with:
          context: ./piggy-webhooks
          build-args: |
            VERSION=${{ steps.version.outputs.value }}
          file: ./piggy-webhooks/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kongz/piggy-webhooks:${{ steps.version.outputs.value }},ghcr.io/kongz/piggy-webhooks:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache